import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/providers";
import {SiteHeader} from "@/components/layouts/site-header";
import {TailwindIndicator} from "@/components/tailwind-indicator";
import {Toaster} from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import type { Metadata, Viewport } from "next";

export const viewport: Viewport = {
    colorScheme: "dark light",
    themeColor: [
        { media: "(prefers-color-scheme: light)", color: "white" },
        { media: "(prefers-color-scheme: dark)", color: "black" },
    ],
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <head/>
          <body
              className={
                  "min-h-screen bg-background font-sans antialiased"
              }
          >
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
          >
              <div className="relative flex min-h-screen flex-col">
                  <SiteHeader/>
                  <main className="flex-1">{children}</main>
              </div>
              <TailwindIndicator/>
          </ThemeProvider>
          <Toaster/>
          </body>
      </html>
  );
}
